/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * winProduto.java
 *
 * Created on 16/07/2010, 15:50:37
 */

package br.com.caminhoneiro;

import br.com.conexao.Conexao;
import br.com.util.JIntField;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhonathas
 */
public class caminhoneiro extends javax.swing.JFrame {

     private int navega = 0; //variavel pra saber o  botão clicado;
     private Conexao conexao;

     // Inserir Data atual
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    // Inserir Data atual

    public caminhoneiro() {
        initComponents(); //Inicializa os componentes da tela
        conexao = new Conexao();
        conexao.conecta("emalhe");

        //Insere nomes do município no cbMunicipio
        AttCb();

        //inicia a conexão com o bd do formulário
        conexao.execute("select * from caminhoneiro");

        try {
            conexao.resultSet.first();
            mostra_dados_caminhoneiro();


        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        definicao = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jpAtravessador = new javax.swing.JPanel();
        tfIdade = new JIntField();
        tfNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Cadastrar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_novo = new javax.swing.JButton();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfNaturalidade = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfAtividadeSecundaria = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfComposicaoFamiliar = new JIntField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfPqParou = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cbLocalMoradia = new javax.swing.JComboBox();
        cbEstadoCivil = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbEscolaridade = new javax.swing.JComboBox();
        rbCaminhao = new javax.swing.JRadioButton();
        rbMoto = new javax.swing.JRadioButton();
        rbCarroParticular = new javax.swing.JRadioButton();
        cbAtividadePrincipal = new javax.swing.JComboBox();
        rbBicicleta = new javax.swing.JRadioButton();
        rbSoTrasporta = new javax.swing.JRadioButton();
        rbSoComercializa = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jp0 = new javax.swing.JPanel();
        tfColetor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDataColetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDigitador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDataDigitador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionário Atravessador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jpAtravessador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpAtravessador.setPreferredSize(new java.awt.Dimension(735, 538));

        tfIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdadeActionPerformed(evt);
            }
        });

        jLabel22.setText("Idade.:");

        jLabel23.setText("Nome.:");

        jLabel24.setText("Município");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAction(evt);
            }
        });

        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_novo.setText("Limpar");
        botao_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_novoActionPerformed(evt);
            }
        });

        botao_primeiro.setText("<<");
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setText("<");
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setText(">");
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setText(">>");
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_excluir)
                        .addGap(7, 7, 7)
                        .addComponent(botao_alterar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_ultimo)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_primeiro)
                    .addComponent(botao_anterior)
                    .addComponent(botao_proximo)
                    .addComponent(botao_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_novo)
                    .addComponent(Cadastrar)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar))
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Dados Pessoais");

        jLabel26.setText("Apelido.:");

        jLabel27.setText("Naturalidade.:");

        jLabel28.setText("Sexo.:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel29.setText("Atividade principal de renda.:");

        jLabel30.setText("Atividade secundária.:");

        jLabel31.setText("Estado civil.:");

        jLabel32.setText("Número de filhos.:");

        jLabel33.setText("Escolaridade.:");

        jLabel34.setText("Porque Parou?");

        jLabel35.setText("Local de Moradia.:");

        cbLocalMoradia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sede Municipal", "Comunidade/Vila local", "Outro Município", "Capital" }));

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "União Estável", "Viúvo" }));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel42.setText("Questionário Caminhoneiro");

        jLabel1.setText("Você é:");

        cbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Analfabeto", "1° Série fundamental", "2° Série fundamental", "3° Série fundamental", "4° Série fundamental", "5° Série fundamental", "6° Série fundamental", "7° Série fundamental", "8° Série fundamental", "1° Série médio", "2° Série médio", "3° Série médio", "Ensino Superior Incompleto", "Ensino Superior Completo" }));

        definicao.add(rbCaminhao);
        rbCaminhao.setText("Caminhão");

        definicao.add(rbMoto);
        rbMoto.setText("Moto");

        definicao.add(rbCarroParticular);
        rbCarroParticular.setText("Carro Particular");

        cbAtividadePrincipal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        definicao.add(rbBicicleta);
        rbBicicleta.setText("Bicicleta");

        buttonGroup1.add(rbSoTrasporta);
        rbSoTrasporta.setText("Só Transporta");

        buttonGroup1.add(rbSoComercializa);
        rbSoComercializa.setText("Transporta e Comercializa");
        rbSoComercializa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSoComercializaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAtravessadorLayout = new javax.swing.GroupLayout(jpAtravessador);
        jpAtravessador.setLayout(jpAtravessadorLayout);
        jpAtravessadorLayout.setHorizontalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtravessadorLayout.createSequentialGroup()
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCaminhao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCarroParticular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbBicicleta))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtravessadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25)
                            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfApelido)
                                    .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEstadoCivil, 0, 222, Short.MAX_VALUE)
                                    .addComponent(cbEscolaridade, 0, 222, Short.MAX_VALUE)
                                    .addComponent(cbAtividadePrincipal, 0, 222, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPqParou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(tfComposicaoFamiliar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                                .addComponent(rbSoTrasporta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSoComercializa)))))
                .addContainerGap())
        );
        jpAtravessadorLayout.setVerticalGroup(
            jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtravessadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbCaminhao)
                    .addComponent(rbMoto)
                    .addComponent(rbCarroParticular)
                    .addComponent(rbBicicleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSoTrasporta)
                    .addComponent(rbSoComercializa))
                .addGap(7, 7, 7)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(tfNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAtravessadorLayout.createSequentialGroup()
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(cbLocalMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(tfAtividadeSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAtividadePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tfComposicaoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAtravessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfPqParou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(cbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jp0.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(tfColetor, gridBagConstraints);

        jLabel5.setText("Data.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jp0.add(tfDataColetor, gridBagConstraints);

        jLabel2.setText("Coletor.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(jLabel2, gridBagConstraints);

        jLabel6.setText("Digitador.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(tfDigitador, gridBagConstraints);

        jLabel7.setText("Data.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jp0.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jp0.add(tfDataDigitador, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jp0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAtravessador, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-751)/2, (screenSize.height-495)/2, 751, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        try{
            String sql ="UPDATE caminhoneiro SET "+
                    "tipo_veiculo = '"+getTrasporte()+"',"+
                    "modo_transporte = '"+getModo()+"',"+
                    "municipio = '"+cbMunicipio.getSelectedItem()+"',"+
                    "nome = '"+tfNome.getText()+"',"+
                    "apelido = '"+ tfApelido.getText() +"',"+
                    "naturalidade = '"+ tfNaturalidade.getText() +"',"+
                    "local_moradia = '"+ cbLocalMoradia.getSelectedItem() +"',"+
                    "sexo = '"+ cbSexo.getSelectedItem() +"',"+
                    "idade = '"+ tfIdade.getText() +"',"+
                    "atividade_principal = '"+ cbAtividadePrincipal.getSelectedItem() +"',"+
                    "atividade_secundaria = '"+ tfAtividadeSecundaria.getText() +"',"+
                    "estado_civil = '"+ cbEstadoCivil.getSelectedItem() +"',"+
                    "composicao_familiar = '"+ tfComposicaoFamiliar.getText() +"',"+
                    "escolaridade = '"+ cbEscolaridade.getSelectedItem() +"',"+

                    "digitador = '"+ tfDigitador.getText()+"',"+
                    "coletor = '"+ tfColetor.getText()+"',"+
                    "data_digitador = '"+ tfDataDigitador.getText()+"',"+
                    "data_coletor = '"+ tfDataColetor.getText()+"',"+

                    "pq_parou = '"+ tfPqParou.getText() +"' "+


                    "where cod_caminhoneiro = "+conexao.resultSet.getString("cod_caminhoneiro");

            System.out.println(sql);
            if (conexao.update(sql)){
                JOptionPane.showMessageDialog(null,"Alterado com sucesso");
                //Atualiza Resultset
                conexao.execute("select * from caminhoneiro");
                conexao.resultSet.next();
                mostra_dados_caminhoneiro();
            }


        }catch (Exception e){
            System.out.println(e + " Erro no botão alterar");
        }
}//GEN-LAST:event_botao_alterarActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
        try {
            conexao.resultSet.last();
            mostra_dados_caminhoneiro();
            navega = 2;

        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
        proximo();
        mostra_dados_caminhoneiro();
        navega = 2;
}//GEN-LAST:event_botao_proximoActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
        anterior();
        mostra_dados_caminhoneiro();
        navega = 1;
}//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
        try {
            conexao.resultSet.first();
            mostra_dados_caminhoneiro();
            navega = 1;

        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_novoActionPerformed
        limpar();
}//GEN-LAST:event_botao_novoActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        String sql;
        try {
            sql = "select * from caminhoneiro Where cod_caminhoneiro =" + conexao.resultSet.getString("cod_caminhoneiro");
            conexao.execute(sql);
            conexao.resultSet.first();
            String nome = "Deletar o caminhoneiro : "+conexao.resultSet.getString("nome")+" ?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                sql = "DELETE FROM caminhoneiro Where cod_caminhoneiro ="+conexao.resultSet.getString("cod_caminhoneiro");
                if (conexao.salvar(sql)) {
                    JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                    //atualiza o ResultSet
                    conexao.execute("select * from caminhoneiro");
                    conexao.resultSet.first();
                    mostra_dados_caminhoneiro();
                }
            } else{
                conexao.execute("select * from caminhoneiro");
                conexao.resultSet.first();
                mostra_dados_caminhoneiro();
            }

        } catch (SQLException ex) {
            System.out.println("Erro ao tentar excluir "+ex);
        }
}//GEN-LAST:event_botao_excluirActionPerformed

    private void CadastrarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAction
        try {
            String sqlinsert = "insert into caminhoneiro "
                    + "(tipo_veiculo,modo_transporte,municipio,nome,apelido,naturalidade,"
                    + "sexo,idade,atividade_principal,atividade_secundaria,"
                    + "estado_civil,composicao_familiar,escolaridade,pq_parou,"
                    + "local_moradia,"
                    + "digitador,coletor,data_digitador,data_coletor) values ('"+
                    getTrasporte()+"','"+
                    getModo()+"','"+
                    cbMunicipio.getSelectedItem()+"','"+
                    tfNome.getText()+"','"+
                    tfApelido.getText()+"','"+
                    tfNaturalidade.getText()+"','"+
                    cbSexo.getSelectedItem()+"',"+
                    tfIdade.getText()+",'"+
                    cbAtividadePrincipal.getSelectedItem()+"','"+
                    tfAtividadeSecundaria.getText()+"','"+
                    cbEstadoCivil.getSelectedItem()+"','"+
                    tfComposicaoFamiliar.getText()+"','"+
                    cbEscolaridade.getSelectedItem()+"','"+
                    tfPqParou.getText()+"','"+
                    cbLocalMoradia.getSelectedItem()+"','"+
                    tfDigitador.getText()+"','"+
                    tfColetor.getText()+"','"+
                    tfDataDigitador.getText()+"','"+
                    tfDataColetor.getText()+"')";

            //System.out.println(sqlinsert);
            if (conexao.salvar(sqlinsert)) {
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
                //agora é hora de atualizar o resultset
                conexao.execute("select * from caminhoneiro");
                conexao.resultSet.first(); //1º registro
                mostra_dados_caminhoneiro();
            }


        }catch (SQLException erro){
            System.out.println(erro);
        }
}//GEN-LAST:event_CadastrarAction

    private void tfIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdadeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tfIdadeActionPerformed

    private void rbSoComercializaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSoComercializaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSoComercializaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frm_caminhoneiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_novo;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbAtividadePrincipal;
    private javax.swing.JComboBox cbEscolaridade;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbLocalMoradia;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.ButtonGroup definicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp0;
    private javax.swing.JPanel jpAtravessador;
    private javax.swing.JRadioButton rbBicicleta;
    private javax.swing.JRadioButton rbCaminhao;
    private javax.swing.JRadioButton rbCarroParticular;
    private javax.swing.JRadioButton rbMoto;
    private javax.swing.JRadioButton rbSoComercializa;
    private javax.swing.JRadioButton rbSoTrasporta;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfAtividadeSecundaria;
    private javax.swing.JTextField tfColetor;
    private javax.swing.JTextField tfComposicaoFamiliar;
    private javax.swing.JTextField tfDataColetor;
    private javax.swing.JTextField tfDataDigitador;
    private javax.swing.JTextField tfDigitador;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNaturalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPqParou;
    // End of variables declaration//GEN-END:variables


    private void mostra_dados_caminhoneiro(){
       //limpar();
       String teste = new String();
        try {

            try {
            teste = conexao.resultSet.getString("tipo_veiculo");
            if (teste.equals(rbCaminhao.getText()))
                rbCaminhao.setSelected(true);
            else if (teste.equals(rbCarroParticular.getText()))
                rbCarroParticular.setSelected(true);
            else if (teste.equals(rbMoto.getText()))
                rbMoto.setSelected(true);
            else if (teste.equals(rbBicicleta.getText()))
                rbBicicleta.setSelected(true);

            teste = conexao.resultSet.getString("modo_transporte");
            if (teste.equals(rbSoTrasporta.getText()))
                rbSoTrasporta.setSelected(true);
            else if (teste.equals(rbSoComercializa.getText()))
                rbSoComercializa.setSelected(true);
            } catch (Exception e) {
            }
            

            tfNome.setText(conexao.resultSet.getString("nome"));
            tfApelido.setText(conexao.resultSet.getString("apelido"));
            tfNaturalidade.setText(conexao.resultSet.getString("naturalidade"));
            tfIdade.setText(conexao.resultSet.getString("idade"));
            cbAtividadePrincipal.setSelectedItem(conexao.resultSet.getString("atividade_principal"));
            tfAtividadeSecundaria.setText(conexao.resultSet.getString("atividade_secundaria"));
            cbEstadoCivil.setSelectedItem(conexao.resultSet.getString("estado_civil"));
            tfComposicaoFamiliar.setText(conexao.resultSet.getString("composicao_familiar"));
            cbEscolaridade.setSelectedItem(conexao.resultSet.getString("escolaridade"));
            tfPqParou.setText(conexao.resultSet.getString("pq_parou"));
            cbMunicipio.setSelectedItem(conexao.resultSet.getString("municipio"));
            cbSexo.setSelectedItem(conexao.resultSet.getString("sexo"));
            cbLocalMoradia.setSelectedItem(conexao.resultSet.getString("local_moradia"));

            tfDigitador.setText(conexao.resultSet.getString("digitador"));
            tfColetor.setText(conexao.resultSet.getString("coletor"));
            tfDataDigitador.setText(conexao.resultSet.getString("data_digitador"));
            tfDataColetor.setText(conexao.resultSet.getString("data_coletor"));


        }catch (SQLException ex) {
            if (navega == 1){
                JOptionPane.showMessageDialog(null,"Você já esta no primeiro registro");
                proximo();
            }
            else if (navega == 2){
                JOptionPane.showMessageDialog(null,"Você já esta no ultimo registro");
                anterior();
            }
            else
                JOptionPane.showMessageDialog(null,"Nenhum registro encontrado "+ ex );
            navega = 0;
            //Logger.getLogger(pescador.class.getName()).log(Level.SEVERE, null, ex);
        }

       //Insere data no digitador, caso não tenha nada
        if (tfDataDigitador.getText().equals(""))
            tfDataDigitador.setText(formatador.format(data));
    }

    private void anterior() {
         try {
                    conexao.resultSet.previous();
                } catch (SQLException ex1) {
                    Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }

    private void proximo() {
        try {
                    conexao.resultSet.next();
                } catch (SQLException ex1) {
                    Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex1);
                }
    }

    private String getTrasporte() {
        String tdefinicao = new String();
        if (rbCaminhao.isSelected())
            tdefinicao = rbCaminhao.getText();
        else if (rbCarroParticular.isSelected())
            tdefinicao = rbCarroParticular.getText();
        else if (rbMoto.isSelected())
            tdefinicao = rbMoto.getText();
        else if (rbBicicleta.isSelected())
            tdefinicao = rbBicicleta.getText();

        return tdefinicao;
    }

        private String getModo() {
        String tdefinicao = new String();
        if (rbSoTrasporta.isSelected())
            tdefinicao = rbSoTrasporta.getText();
        else if (rbSoComercializa.isSelected())
            tdefinicao = rbSoComercializa.getText();

        return tdefinicao;
    }

    private void limpar() {
        tfNome.setText("");
        tfApelido.setText("");
        tfNaturalidade.setText("");
        tfIdade.setText("0");
        cbAtividadePrincipal.setSelectedIndex(0);
        tfAtividadeSecundaria.setText("");
        cbEstadoCivil.setSelectedIndex(0);
        tfComposicaoFamiliar.setText("");
        cbEscolaridade.setSelectedIndex(0);
        tfPqParou.setText("");
        cbMunicipio.setSelectedIndex(0);
        cbSexo.setSelectedIndex(0);
        cbLocalMoradia.setSelectedIndex(0);
        cbEscolaridade.setSelectedIndex(0);
        rbCaminhao.setSelected(false);
        rbCarroParticular.setSelected(false);
        rbMoto.setSelected(false);
    }

    private void AttCb() {
        try {
            cbMunicipio.removeAllItems();
            conexao.execute("select * FROM municipios where pai='Pará' or pai='Maranhão' or pai='Amapá' ");
            while (conexao.resultSet.next()){
                cbMunicipio.addItem(conexao.resultSet.getString("nome"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            cbAtividadePrincipal.removeAllItems();
            conexao.execute("select * FROM atividade ");
            while (conexao.resultSet.next()){
                cbAtividadePrincipal.addItem(conexao.resultSet.getString("atividade"));
            }
        }catch (SQLException ex) {
            Logger.getLogger(caminhoneiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    



}
