
package br.com.formulario.fabricaDeGelo;

import br.com.conexao.Conexao;
import br.com.util.JIntField;
import br.com.util.JMoneyField;
import br.com.util.Utilidade;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MPA
 */

public class fabricaDeGelo2 extends javax.swing.JFrame {

    /** Creates new form frm_questionario_atravessador Go Your Own Way*/
    private Conexao conexao;
    int inicia_combo = 0;
    String id_atravessador;
    String ItemDoCb;
    private Utilidade util = new Utilidade();

    public fabricaDeGelo2() {
        initComponents();
        conexao = new Conexao();
        conexao.conecta("emalhe");

        //Insere nome no cbNomeAtravessador
        attCbAtravessador();
        mostra_dados();

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        casa = new javax.swing.ButtonGroup();
        banheiro = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpPescadoSubproduto = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        cbNomeEmpresa = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        botao_salvar_questionario = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        tfQ10 = new JIntField();
        jLabel54 = new javax.swing.JLabel();
        tfSalario = new JMoneyField();
        jLabel55 = new javax.swing.JLabel();
        tfNumero = new JIntField();
        btExcluirRendaFamilia = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        btAdicionarRendaFamilia = new javax.swing.JButton();
        jScrollPane30 = new javax.swing.JScrollPane();
        jtNumeroFuncionarios = new javax.swing.JTable();
        jLabel59 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbFuncao = new javax.swing.JComboBox();
        tfHorasTrabalhadas = new JIntField();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taQ11 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taQ12 = new javax.swing.JTextArea();
        jLabel70 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taQ13 = new javax.swing.JTextArea();
        jLabel74 = new javax.swing.JLabel();
        ckbQ14Filtragem = new javax.swing.JCheckBox();
        ckbQ14Cloro = new javax.swing.JCheckBox();
        ckbQ14Ozonio = new javax.swing.JCheckBox();
        ckbQ14Outros = new javax.swing.JCheckBox();
        tfQ14 = new javax.swing.JTextField();
        ckbQ15Pescador = new javax.swing.JCheckBox();
        jLabel75 = new javax.swing.JLabel();
        ckbQ15Marreteiro = new javax.swing.JCheckBox();
        ckbQ15Caminhao = new javax.swing.JCheckBox();
        ckbQ15Outros = new javax.swing.JCheckBox();
        tfQ15 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        ckbQ16Sim = new javax.swing.JCheckBox();
        tfQ16 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        tfValor = new JMoneyField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        tfDesconto = new JMoneyField();
        btExcluirRendaFamilia1 = new javax.swing.JButton();
        jScrollPane35 = new javax.swing.JScrollPane();
        jtAbatimento = new javax.swing.JTable();
        btAdicionarRendaFamilia1 = new javax.swing.JButton();
        cbCusto = new javax.swing.JComboBox();
        tfAno = new JIntField();
        jLabel14 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        jtEmprestimo = new javax.swing.JTable();
        btExcluirRendaFamilia2 = new javax.swing.JButton();
        ckbQ18Sim = new javax.swing.JCheckBox();
        jp18 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        tfCapGiro = new JMoneyField();
        jtEmprestimoEmpresa = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        tfEquipamentos = new javax.swing.JTextField();
        cbEmprestimo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfOutros = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        tfConstrucao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fabrica de Gêlo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setText("Questionário Fabrica de Gêlo");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel41)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cbNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeEmpresaActionPerformed(evt);
            }
        });

        jLabel8.setText("Empresa.:");

        botao_salvar_questionario.setText("Salvar");
        botao_salvar_questionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvar_questionarioActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel49.setText("9 - Qual o número de funcionários por setor.");

        tfQ10.setText("0");

        jLabel54.setText("Salário.:");

        jLabel55.setText("Número.:");

        btExcluirRendaFamilia.setText("Excluir");
        btExcluirRendaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirRendaFamiliaActionPerformed(evt);
            }
        });

        jLabel56.setText("Função.:");

        btAdicionarRendaFamilia.setText("Adicionar");
        btAdicionarRendaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarRendaFamiliaActionPerformed(evt);
            }
        });

        jtNumeroFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Função", "Salário", "Número", "Horas Trabalhadas"
            }
        ));
        jScrollPane30.setViewportView(jtNumeroFuncionarios);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel59.setText("10 - Qual a média do tempo de permanência dos funcionários da empresa em anos.");

        jLabel11.setText("Horas Trabalhadas.:");

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administração", "Produção", "Vigilante", "Serviços Gerais" }));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel68.setText("11 - Qual os principais problemas que enfrenta com a fábrica de gelo");

        taQ11.setColumns(20);
        taQ11.setRows(5);
        jScrollPane3.setViewportView(taQ11);

        taQ12.setColumns(20);
        taQ12.setRows(5);
        jScrollPane4.setViewportView(taQ12);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel70.setText("12 - Como solucionar os problemas (gargalos):");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel73.setText("13 - Qual a origem da água utilizada para a fabricação do gelo?");

        taQ13.setColumns(20);
        taQ13.setRows(5);
        jScrollPane5.setViewportView(taQ13);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel74.setText("14 - A água passa por algum tipo de tratamento? Qual?");

        ckbQ14Filtragem.setText("Filtragem");

        ckbQ14Cloro.setText("Cloro");

        ckbQ14Ozonio.setText("Ozônio");

        ckbQ14Outros.setText("Outros");
        ckbQ14Outros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbQ14OutrosStateChanged(evt);
            }
        });

        tfQ14.setEditable(false);

        ckbQ15Pescador.setText("Pescador");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel75.setText("15 - Quais os principais clientes?");

        ckbQ15Marreteiro.setText("Marreteiro");

        ckbQ15Caminhao.setText("Caminhão");

        ckbQ15Outros.setText("Outros");
        ckbQ15Outros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbQ15OutrosStateChanged(evt);
            }
        });

        tfQ15.setEditable(false);

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel76.setText("16 - A empresa recebeu incentivos fiscais?");

        ckbQ16Sim.setText("Sim. Qual?");
        ckbQ16Sim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbQ16SimStateChanged(evt);
            }
        });

        tfQ16.setEditable(false);

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel77.setText("17 - A empresa recebe algum abatimento nos custos?");

        jLabel57.setText("Desconto.:");

        jLabel58.setText("Valor.:");

        jLabel60.setText("Custos.:");

        btExcluirRendaFamilia1.setText("Excluir");
        btExcluirRendaFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirRendaFamilia1ActionPerformed(evt);
            }
        });

        jtAbatimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Custos", "Valor", "Desconto", "Ano"
            }
        ));
        jScrollPane35.setViewportView(jtAbatimento);

        btAdicionarRendaFamilia1.setText("Adicionar");
        btAdicionarRendaFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarRendaFamilia1ActionPerformed(evt);
            }
        });

        cbCusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Luz", "ICMS", "IPTU", "Outros" }));

        jLabel14.setText("A partir de (ano).:");

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel78.setText("18 - Fez algum empréstimo para a empresa?");

        jtEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Empréstimo", "Construção", "Equipamentos", "Cap.Giro", "Outros"
            }
        ));
        jScrollPane36.setViewportView(jtEmprestimo);

        btExcluirRendaFamilia2.setText("Excluir");
        btExcluirRendaFamilia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirRendaFamilia2ActionPerformed(evt);
            }
        });

        ckbQ18Sim.setText("Sim");

        jp18.setLayout(new java.awt.GridBagLayout());

        jLabel62.setText("Equipamentos.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jp18.add(jLabel62, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 0);
        jp18.add(tfCapGiro, gridBagConstraints);

        jtEmprestimoEmpresa.setText("Adicionar");
        jtEmprestimoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmprestimoEmpresaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        jp18.add(jtEmprestimoEmpresa, gridBagConstraints);

        jLabel63.setText("Construção.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jp18.add(jLabel63, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 0);
        jp18.add(tfEquipamentos, gridBagConstraints);

        cbEmprestimo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco", "Linha de credito (FNO, Finame)", "Valor do empréstimo", "Data do empréstimo", "Carência", "Prestações", "Quantas Pagou", "Em dia/Atrasado/Inadimplente" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jp18.add(cbEmprestimo, gridBagConstraints);

        jLabel1.setText("Empréstimo.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jp18.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 0);
        jp18.add(tfOutros, gridBagConstraints);

        jLabel15.setText("Outros.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        jp18.add(jLabel15, gridBagConstraints);

        jLabel61.setText("Cap. Giro.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 5);
        jp18.add(jLabel61, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 0);
        jp18.add(tfConstrucao, gridBagConstraints);

        javax.swing.GroupLayout jpPescadoSubprodutoLayout = new javax.swing.GroupLayout(jpPescadoSubproduto);
        jpPescadoSubproduto.setLayout(jpPescadoSubprodutoLayout);
        jpPescadoSubprodutoLayout.setHorizontalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(botao_alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_salvar_questionario))
                            .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(119, 119, 119))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                                .addComponent(btExcluirRendaFamilia)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(jLabel56)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                            .addComponent(jLabel55)
                                            .addGap(57, 57, 57)
                                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfHorasTrabalhadas)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                    .addComponent(btAdicionarRendaFamilia))
                                .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(137, 137, 137))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQ10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(188, Short.MAX_VALUE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel68, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel70))
                        .addContainerGap(337, Short.MAX_VALUE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(jLabel73))
                        .addGap(333, 333, 333))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ckbQ15Marreteiro)
                                .addComponent(ckbQ15Caminhao)
                                .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(ckbQ15Pescador)
                                    .addGap(18, 18, 18)
                                    .addComponent(ckbQ15Outros)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQ15, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                .addComponent(jLabel75))
                            .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ckbQ14Ozonio)
                                .addComponent(ckbQ14Cloro)
                                .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                    .addComponent(ckbQ14Filtragem)
                                    .addGap(18, 18, 18)
                                    .addComponent(ckbQ14Outros)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQ14))
                                .addComponent(jLabel74)))
                        .addGap(407, 407, 407))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addComponent(ckbQ16Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQ16))
                            .addComponent(jLabel76))
                        .addContainerGap(482, Short.MAX_VALUE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addContainerGap(418, Short.MAX_VALUE))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbQ18Sim)
                        .addGap(423, 423, 423))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                            .addComponent(btExcluirRendaFamilia1)
                            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                                        .addComponent(jLabel60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfValor)
                                            .addComponent(cbCusto, 0, 100, Short.MAX_VALUE)))
                                    .addComponent(jLabel58))
                                .addGap(18, 18, 18)
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel57))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAno)
                                    .addComponent(tfDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(btAdicionarRendaFamilia1))
                            .addComponent(jp18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                            .addComponent(btExcluirRendaFamilia2))
                        .addGap(104, 104, 104))))
        );
        jpPescadoSubprodutoLayout.setVerticalGroup(
            jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(btAdicionarRendaFamilia)
                            .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tfHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirRendaFamilia)
                .addGap(24, 24, 24)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(tfQ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel74)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ14Filtragem)
                    .addComponent(ckbQ14Outros)
                    .addComponent(tfQ14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbQ14Cloro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbQ14Ozonio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ15Pescador)
                    .addComponent(ckbQ15Outros)
                    .addComponent(tfQ15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbQ15Caminhao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbQ15Marreteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ16Sim)
                    .addComponent(tfQ16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(btAdicionarRendaFamilia1)
                            .addComponent(cbCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPescadoSubprodutoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57)
                        .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirRendaFamilia1)
                .addGap(18, 18, 18)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(ckbQ18Sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirRendaFamilia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPescadoSubprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_salvar_questionario)
                    .addComponent(botao_alterar))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jpPescadoSubproduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-716)/2, (screenSize.height-788)/2, 716, 788);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeEmpresaActionPerformed
       
        //Pesquisa automática do Combo Box Nome do atravessador
        
        if (inicia_combo == 1){
         mostra_dados();
        }inicia_combo = 1;
         
    }//GEN-LAST:event_cbNomeEmpresaActionPerformed

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void botao_salvar_questionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvar_questionarioActionPerformed
        salvar_dados();
    }//GEN-LAST:event_botao_salvar_questionarioActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        atualizar_dados();
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void btExcluirRendaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirRendaFamiliaActionPerformed
        DeljtNumeroFuncionarios();
}//GEN-LAST:event_btExcluirRendaFamiliaActionPerformed

    private void btAdicionarRendaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarRendaFamiliaActionPerformed
        AddjtNumeroFuncionarios();
}//GEN-LAST:event_btAdicionarRendaFamiliaActionPerformed

    private void btExcluirRendaFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirRendaFamilia1ActionPerformed
        DeljtAbatimento();
    }//GEN-LAST:event_btExcluirRendaFamilia1ActionPerformed

    private void btAdicionarRendaFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarRendaFamilia1ActionPerformed
        AddjtAbatimento();
    }//GEN-LAST:event_btAdicionarRendaFamilia1ActionPerformed

    private void jtEmprestimoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmprestimoEmpresaActionPerformed
        AddjtEmprestimoEmpresa();
    }//GEN-LAST:event_jtEmprestimoEmpresaActionPerformed

    private void btExcluirRendaFamilia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirRendaFamilia2ActionPerformed
        DeljtEmprestimoEmpresa();
    }//GEN-LAST:event_btExcluirRendaFamilia2ActionPerformed

    private void ckbQ14OutrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbQ14OutrosStateChanged
        if (ckbQ14Outros.isSelected()){
            tfQ14.setEditable(true);
        }else{
            tfQ14.setEditable(false);
            tfQ14.setText("");
        }
    }//GEN-LAST:event_ckbQ14OutrosStateChanged

    private void ckbQ15OutrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbQ15OutrosStateChanged
        if (ckbQ15Outros.isSelected()){
            tfQ15.setEditable(true);
        }else{
            tfQ15.setEditable(false);
            tfQ15.setText("");
        }
    }//GEN-LAST:event_ckbQ15OutrosStateChanged

    private void ckbQ16SimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbQ16SimStateChanged
        if (ckbQ16Sim.isSelected()){
            tfQ16.setEditable(true);
        }else{
            tfQ16.setEditable(false);
            tfQ16.setText("");
        }
    }//GEN-LAST:event_ckbQ16SimStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fabricaDeGelo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup banheiro;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_salvar_questionario;
    private javax.swing.JButton btAdicionarRendaFamilia;
    private javax.swing.JButton btAdicionarRendaFamilia1;
    private javax.swing.JButton btExcluirRendaFamilia;
    private javax.swing.JButton btExcluirRendaFamilia1;
    private javax.swing.JButton btExcluirRendaFamilia2;
    private javax.swing.ButtonGroup casa;
    private javax.swing.JComboBox cbCusto;
    private javax.swing.JComboBox cbEmprestimo;
    private javax.swing.JComboBox cbFuncao;
    private javax.swing.JComboBox cbNomeEmpresa;
    private javax.swing.JCheckBox ckbQ14Cloro;
    private javax.swing.JCheckBox ckbQ14Filtragem;
    private javax.swing.JCheckBox ckbQ14Outros;
    private javax.swing.JCheckBox ckbQ14Ozonio;
    private javax.swing.JCheckBox ckbQ15Caminhao;
    private javax.swing.JCheckBox ckbQ15Marreteiro;
    private javax.swing.JCheckBox ckbQ15Outros;
    private javax.swing.JCheckBox ckbQ15Pescador;
    private javax.swing.JCheckBox ckbQ16Sim;
    private javax.swing.JCheckBox ckbQ18Sim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPanel jp18;
    private javax.swing.JPanel jpPescadoSubproduto;
    private javax.swing.JTable jtAbatimento;
    private javax.swing.JTable jtEmprestimo;
    private javax.swing.JButton jtEmprestimoEmpresa;
    private javax.swing.JTable jtNumeroFuncionarios;
    private javax.swing.JTextArea taQ11;
    private javax.swing.JTextArea taQ12;
    private javax.swing.JTextArea taQ13;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfCapGiro;
    private javax.swing.JTextField tfConstrucao;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfEquipamentos;
    private javax.swing.JTextField tfHorasTrabalhadas;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfOutros;
    private javax.swing.JTextField tfQ10;
    private javax.swing.JTextField tfQ14;
    private javax.swing.JTextField tfQ15;
    private javax.swing.JTextField tfQ16;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables


    private void mostra_dados(){
        limpar_dados();
        AttjtEmprestimoEmpresa();
        AttjtAbatimento();
        AttjtNumeroFuncionarios();

        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
        System.out.println(codigo);
                    
        try {
            //Atravessador Moradia
            conexao.execute("SELECT * FROM fabrica_gelo_questionario WHERE cod_fabrica_gelo = "+codigo);
            conexao.resultSet.first();

            tfQ10.setText(conexao.resultSet.getString("tempo_permanencia"));
            taQ11.setText(conexao.resultSet.getString("principais_problemas"));
            taQ12.setText(conexao.resultSet.getString("solucao_problemas"));
            taQ13.setText(conexao.resultSet.getString("origem_da_agua"));

            if (conexao.resultSet.getString("tratamento_agua_filtragem").equals("1"))
                   ckbQ14Filtragem.setSelected(true);

            if (conexao.resultSet.getString("tratamento_agua_cloro").equals("1"))
                   ckbQ14Cloro.setSelected(true);

            if (conexao.resultSet.getString("tratamento_agua_ozonio").equals("1"))
                   ckbQ14Ozonio.setSelected(true);

            if (conexao.resultSet.getString("tratamento_agua_outro").equals("1"))
                   ckbQ14Outros.setSelected(true);

            tfQ14.setText(conexao.resultSet.getString("tratamento_agua_outro_qual"));

            if (conexao.resultSet.getString("principais_clientes_pescador").equals("1"))
                   ckbQ15Pescador.setSelected(true);

            if (conexao.resultSet.getString("principais_clientes_caminhao").equals("1"))
                   ckbQ15Caminhao.setSelected(true);
       
            if (conexao.resultSet.getString("principais_clientes_marreteiro").equals("1"))
                   ckbQ15Marreteiro.setSelected(true);

            if (conexao.resultSet.getString("principais_clientes_outro").equals("1"))
                   ckbQ15Outros.setSelected(true);

            tfQ15.setText(conexao.resultSet.getString("principais_clientes_outro_qual"));
 
            if (conexao.resultSet.getString("recebeu_incentivos_fiscais").equals("1"))
                   ckbQ16Sim.setSelected(true);
            
            if (conexao.resultSet.getString("fez_emprestimo").equals("1"))
                   ckbQ18Sim.setSelected(true);

 
        } catch (Exception e) {
            System.out.println(e + " metodo mostrar dados");
        }
    }

        public void limpar_dados(){

            tfQ10.setText("");
            taQ11.setText("");
            taQ12.setText("");
            taQ13.setText("");
            ckbQ14Filtragem.setSelected(false);
            ckbQ14Cloro.setSelected(false);
            ckbQ14Ozonio.setSelected(false);
            ckbQ14Outros.setSelected(false);
            ckbQ15Pescador.setSelected(false);
            ckbQ15Caminhao.setSelected(false);
            ckbQ15Marreteiro.setSelected(false);
            ckbQ15Outros.setSelected(false);
            ckbQ16Sim.setSelected(false);
            ckbQ18Sim.setSelected(false);

    }
        
    private void attCbAtravessador() {
         try {
                    cbNomeEmpresa.removeAllItems();
                    conexao.execute("select * from fabrica_gelo");

                    while (conexao.resultSet.next()){
                        cbNomeEmpresa.addItem(conexao.resultSet.getString("cod_fabrica_gelo")+
                                                       " # "+ conexao.resultSet.getString("nome_empresa"));

                    }
                }catch (SQLException ex) {
                    System.out.println(ex);
                }
    }

    private void DeljtNumeroFuncionarios() {
    //System.out.println(jTableAtividadeFamiliar.getValueAt(jTableAtividadeFamiliar.getSelectedRow(),0));
        String sql;

        sql = "delete from fabrica_gelo_numero_funcionarios "
            + "Where cod_fabrica_gelo_numero_funcionarios = "
            + jtNumeroFuncionarios.getValueAt(jtNumeroFuncionarios.getSelectedRow(),0);

            if (conexao.salvar(sql)) {
                System.out.println("Exclusão realizada com sucesso");
                AttjtNumeroFuncionarios();
            }   else
                    JOptionPane.showMessageDialog(null,"Erro na exclusão");
    }

    private void AddjtNumeroFuncionarios() {
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
        System.out.println(codigo);


        String sqlinsert = "insert into fabrica_gelo_numero_funcionarios "
                  + "(cod_fabrica_gelo,funcao,salario,numero,"
                  + "horas_trabalhadas) values ("+
                  codigo+",'"+
                  cbFuncao.getSelectedItem()+"','"+
                  tfSalario.getText()+"','"+
                  tfNumero.getText()+"','"+
                  tfHorasTrabalhadas.getText()+"')";

        //System.out.println(sqlinsert);
        if (conexao.salvar(sqlinsert)) {
            System.out.println("Jtable - Cadastrado com sucesso");
            AttjtNumeroFuncionarios();
        }
    }

    private void AttjtNumeroFuncionarios() {
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());

        conexao.execute("select * from fabrica_gelo_numero_funcionarios"
                        + " where cod_fabrica_gelo = " + codigo);

        jtNumeroFuncionarios.getColumnModel().getColumn(0).setMaxWidth(0);
        jtNumeroFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtNumeroFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtNumeroFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtNumeroFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtNumeroFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtNumeroFuncionarios.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("cod_fabrica_gelo_numero_funcionarios"),
                                           conexao.resultSet.getString("funcao"),
                                           conexao.resultSet.getString("salario"),
                                           conexao.resultSet.getString("numero"),
                                           conexao.resultSet.getString("horas_trabalhadas"),
                                          });

            conexao.resultSet.first();

        }catch (SQLException erro){
            System.out.println(erro + "Tabela Familia Renda Trabalho");
            //attjTableComposicaoPescaria();
        }
    }

    private void AddjtAbatimento() {
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
        System.out.println(codigo);


        String sqlinsert = "insert into fabrica_gelo_abatimento "
                  + "(cod_fabrica_gelo,custos,valor,desconto,"
                  + "ano) values ("+
                  codigo+",'"+
                  cbCusto.getSelectedItem()+"','"+
                  tfValor.getText()+"','"+
                  tfDesconto.getText()+"','"+
                  tfAno.getText()+"')";

        //System.out.println(sqlinsert);
        if (conexao.salvar(sqlinsert)) {
            System.out.println("Jtable - Cadastrado com sucesso");
            AttjtAbatimento();
        }
    }


    private void AttjtAbatimento(){
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());

        conexao.execute("select * from fabrica_gelo_abatimento"
                        + " where cod_fabrica_gelo = " + codigo);

        jtAbatimento.getColumnModel().getColumn(0).setMaxWidth(0);
        jtAbatimento.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtAbatimento.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtAbatimento.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtAbatimento.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtAbatimento.getColumnModel().getColumn(4).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtAbatimento.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("cod_fabrica_gelo_abatimento"),
                                           conexao.resultSet.getString("custos"),
                                           conexao.resultSet.getString("valor"),
                                           conexao.resultSet.getString("desconto"),
                                           conexao.resultSet.getString("ano"),
                                          });

            conexao.resultSet.first();

        }catch (SQLException erro){
            System.out.println(erro + "Tabela Familia Renda Trabalho");
        }
    }

   private void DeljtAbatimento(){
    //System.out.println(jTableAtividadeFamiliar.getValueAt(jTableAtividadeFamiliar.getSelectedRow(),0));
        String sql;

        sql = "delete from fabrica_gelo_abatimento "
            + "Where cod_fabrica_gelo_abatimento = "
            + jtAbatimento.getValueAt(jtAbatimento.getSelectedRow(),0);

            if (conexao.salvar(sql)) {
                System.out.println("Exclusão realizada com sucesso");
                AttjtAbatimento();
            }   else
                    JOptionPane.showMessageDialog(null,"Erro na exclusão");
    }

    private void AddjtEmprestimoEmpresa() {
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
        System.out.println(codigo);


        String sqlinsert = "insert into fabrica_gelo_emprestimo "
                  + "(cod_fabrica_gelo,emprestimo,construcao,equipamentos,"
                  + "cap_giro,outros) values ("+
                  codigo+",'"+
                  cbEmprestimo.getSelectedItem()+"','"+
                  tfConstrucao.getText()+"','"+
                  tfEquipamentos.getText()+"','"+
                  tfCapGiro.getText()+"','"+
                  tfOutros.getText()+"')";

        //System.out.println(sqlinsert);
        if (conexao.salvar(sqlinsert)) {
            System.out.println("Jtable - Cadastrado com sucesso");
            AttjtEmprestimoEmpresa();
        }
    }

    private void AttjtEmprestimoEmpresa() {
        String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());

        conexao.execute("select * from fabrica_gelo_emprestimo"
                        + " where cod_fabrica_gelo = " + codigo);

        jtEmprestimo.getColumnModel().getColumn(0).setMaxWidth(0);
        jtEmprestimo.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtEmprestimo.getColumnModel().getColumn(1).setPreferredWidth(10);
        jtEmprestimo.getColumnModel().getColumn(2).setPreferredWidth(10);
        jtEmprestimo.getColumnModel().getColumn(3).setPreferredWidth(10);
        jtEmprestimo.getColumnModel().getColumn(4).setPreferredWidth(10);
        jtEmprestimo.getColumnModel().getColumn(5).setPreferredWidth(10);

        DefaultTableModel modelo = (DefaultTableModel)jtEmprestimo.getModel();
        modelo.setNumRows(0);//limpa o JTable;

        try{
            while (conexao.resultSet.next())
                modelo.addRow(new Object[]{conexao.resultSet.getString("cod_fabrica_gelo_emprestimo"),
                                           conexao.resultSet.getString("emprestimo"),
                                           conexao.resultSet.getString("construcao"),
                                           conexao.resultSet.getString("equipamentos"),
                                           conexao.resultSet.getString("cap_giro"),
                                           conexao.resultSet.getString("outros"),
                                          });

            conexao.resultSet.first();

        }catch (SQLException erro){
            System.out.println(erro + "Tabela Familia Renda Trabalho");
        }
    }

   private void DeljtEmprestimoEmpresa(){
    //System.out.println(jTableAtividadeFamiliar.getValueAt(jTableAtividadeFamiliar.getSelectedRow(),0));
        String sql;

        sql = "delete from fabrica_gelo_emprestimo "
            + "Where cod_fabrica_gelo_emprestimo = "
            + jtEmprestimo.getValueAt(jtEmprestimo.getSelectedRow(),0);

            if (conexao.salvar(sql)) {
                System.out.println("Exclusão realizada com sucesso");
                AttjtEmprestimoEmpresa();
            }   else
                    JOptionPane.showMessageDialog(null,"Erro na exclusão");
    }

    private void salvar_dados() {
    String sqlinsert = new String();
    String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
    System.out.println(codigo);

        //Questionario 

            sqlinsert = "insert into fabrica_gelo_questionario "
                    + "(cod_fabrica_gelo,tempo_permanencia,"
                    + "principais_problemas,solucao_problemas,origem_da_agua,"
                    + "tratamento_agua_filtragem,tratamento_agua_cloro,"
                    + "tratamento_agua_ozonio,tratamento_agua_outro,"
                    + "tratamento_agua_outro_qual,principais_clientes_pescador,"
                    + "principais_clientes_caminhao,principais_clientes_marreteiro,"
                    + "principais_clientes_outro,principais_clientes_outro_qual,"
                    + "recebeu_incentivos_fiscais,fez_emprestimo) values ("+
                    codigo+",'"+
                    tfQ10.getText()+"','"+
                    taQ11.getText()+"','"+
                    taQ12.getText()+"','"+
                    taQ13.getText()+"','"+
                    util.checarCkb(ckbQ14Filtragem)+"','"+
                    util.checarCkb(ckbQ14Cloro)+"','"+
                    util.checarCkb(ckbQ14Ozonio)+"','"+
                    util.checarCkb(ckbQ14Outros)+"','"+
                    tfQ14.getText()+"','"+
                    util.checarCkb(ckbQ15Pescador)+"','"+
                    util.checarCkb(ckbQ15Caminhao)+"','"+
                    util.checarCkb(ckbQ15Marreteiro)+"','"+
                    util.checarCkb(ckbQ15Outros)+"','"+
                    tfQ15.getText()+"','"+
                    util.checarCkb(ckbQ16Sim)+"','"+
                    util.checarCkb(ckbQ18Sim)+"')";


            //System.out.println(sqlinsert);
            if (conexao.salvar(sqlinsert)) {
                JOptionPane.showMessageDialog(null,"Salvo sucesso" );
                System.out.println("Cadastrado com sucesso");
                mostra_dados();
            }


    }

    private void atualizar_dados() {
    String sqlupdate = new String();
    String codigo = util.separa(1,cbNomeEmpresa.getSelectedItem().toString());
    System.out.println(codigo);

            sqlupdate ="UPDATE fabrica_gelo_questionario SET "
                    +"tempo_permanencia = '"+tfQ10.getText()+"',"
                    +"principais_problemas = '"+taQ11.getText()+"',"
                    +"solucao_problemas = '"+taQ12.getText()+"',"
                    +"origem_da_agua = '"+taQ13.getText()+"',"
                    +"tratamento_agua_filtragem = '"+util.checarCkb(ckbQ14Filtragem)+"',"
                    +"tratamento_agua_cloro = '"+util.checarCkb(ckbQ14Cloro)+"',"
                    +"tratamento_agua_ozonio = '"+util.checarCkb(ckbQ14Ozonio)+"',"
                    +"tratamento_agua_outro = '"+util.checarCkb(ckbQ14Outros)+"',"
                    +"tratamento_agua_outro_qual = '"+tfQ14.getText()+"',"
                    +"principais_clientes_pescador = '"+util.checarCkb(ckbQ15Pescador)+"',"
                    +"principais_clientes_caminhao = '"+util.checarCkb(ckbQ15Caminhao)+"',"
                    +"principais_clientes_marreteiro ='"+util.checarCkb(ckbQ15Marreteiro)+"',"
                    +"principais_clientes_outro ='"+util.checarCkb(ckbQ15Outros)+"',"
                    +"principais_clientes_outro_qual ='"+tfQ15.getText()+"',"
                    +"recebeu_incentivos_fiscais ='"+util.checarCkb(ckbQ16Sim)+"',"
                    +"fez_emprestimo ='"+util.checarCkb(ckbQ18Sim)+"' "+


                    "where cod_fabrica_gelo = "+codigo;


            //System.out.println(sqlupdate);
            if (conexao.update(sqlupdate)){
                JOptionPane.showMessageDialog(null,"Atualizado com sucesso" );
                System.out.println("Comércio - Atualizado com sucesso");
                //Atualiza Resultset
                mostra_dados();
            }

    }
   

}
