package br.com.formulario.pescador;

import br.com.conexao.Conexao;
import br.com.util.Utilidade;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Jhonathas
 */
public class pescador3 extends javax.swing.JFrame {

    private Utilidade util = new Utilidade();
    private int inicia_combo = 0;
    private Conexao conexao;

    public pescador3() {
        initComponents(); //Inicializa os componentes da tela
        conexao = new Conexao();
        conexao.conecta("emalhe");

        //Insere nome do pescador no cbPescador
        attCbPescador();
        mostra_dados();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_questao_1 = new javax.swing.ButtonGroup();
        grupo_questao_2 = new javax.swing.ButtonGroup();
        grupo_questao_3 = new javax.swing.ButtonGroup();
        grupo_questao_4 = new javax.swing.ButtonGroup();
        grupo_questao_5 = new javax.swing.ButtonGroup();
        g11 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cbPescador = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taQuestao5 = new javax.swing.JTextArea();
        rbQ1sim = new javax.swing.JRadioButton();
        rbQ1nao = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        rbQ2Aumentando = new javax.swing.JRadioButton();
        rbQ2Diminuindo = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        rbQ3Sim = new javax.swing.JRadioButton();
        rbQ3Nao = new javax.swing.JRadioButton();
        ckbQ3TrocadeOleo = new javax.swing.JCheckBox();
        ckbQ3TrocadePescado = new javax.swing.JCheckBox();
        ckbQ3TrocadeAlimentos = new javax.swing.JCheckBox();
        ckbQ3Rebocar = new javax.swing.JCheckBox();
        ckbQ3Outros = new javax.swing.JCheckBox();
        rbQ4Sim = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        ckbQ4Outros = new javax.swing.JCheckBox();
        ckbQ4PorRoubodeRede = new javax.swing.JCheckBox();
        ckbQ4PorPesqueiros = new javax.swing.JCheckBox();
        rbQ4Nao = new javax.swing.JRadioButton();
        ckbQ4PorSobreposicaoDeRedeEEspinhel = new javax.swing.JCheckBox();
        ckbQ4PorSobreposicaodeRedes = new javax.swing.JCheckBox();
        rbQ5Sim = new javax.swing.JRadioButton();
        rbQ5Nao = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taQuestao6 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taQuestao7 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taQuestao8 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        taQuestao9 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        taQuestao10 = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btAtualizar = new javax.swing.JButton();
        ckbQuestao11DeCrescimento = new javax.swing.JRadioButton();
        ckbQuestao11Estabilizacao = new javax.swing.JRadioButton();
        ckbQuestao11DeDiminuicao = new javax.swing.JRadioButton();
        rbq1ns = new javax.swing.JRadioButton();
        rbq2ns = new javax.swing.JRadioButton();
        rbQ11ns = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionário Atravessador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar_janela(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        cbPescador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPescadorItemStateChanged(evt);
            }
        });
        cbPescador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPescadorActionPerformed(evt);
            }
        });

        jLabel24.setText("Pesacador");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel42.setText("Questionário Pescador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel42)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel43.setText("Percepção e Perspectivas:");

        jLabel25.setText("1 - Percebeu aumento no número de pescadores nos últimos 10 anos? ");

        taQuestao5.setColumns(20);
        taQuestao5.setRows(5);
        jScrollPane5.setViewportView(taQuestao5);

        grupo_questao_1.add(rbQ1sim);
        rbQ1sim.setText("Sim");

        grupo_questao_1.add(rbQ1nao);
        rbQ1nao.setText("Não");

        jLabel26.setText("2 - O número de barcos está aumentando ou diminuindo em relação a 10 anos atrás?");

        grupo_questao_2.add(rbQ2Aumentando);
        rbQ2Aumentando.setText("Aumentando");

        grupo_questao_2.add(rbQ2Diminuindo);
        rbQ2Diminuindo.setText("Diminuindo");

        jLabel27.setText("3 - Existe alguma interação entre os pescadores em relação à troca, cooperação dos produtos?");

        grupo_questao_3.add(rbQ3Sim);
        rbQ3Sim.setText("Sim");

        grupo_questao_3.add(rbQ3Nao);
        rbQ3Nao.setText("Não");

        ckbQ3TrocadeOleo.setText("Troca de óleo");

        ckbQ3TrocadePescado.setText("Troca de pescado ou grude");

        ckbQ3TrocadeAlimentos.setText("Troca de alimentos");

        ckbQ3Rebocar.setText("Rebocar");

        ckbQ3Outros.setText("Outros");

        grupo_questao_4.add(rbQ4Sim);
        rbQ4Sim.setText("Sim");

        jLabel28.setText("4 - Existe alguma competitividade/rivalidade entre os pescadores?");

        ckbQ4Outros.setText("Outros");

        ckbQ4PorRoubodeRede.setText("Por roubo de rede");

        ckbQ4PorPesqueiros.setText("Por pesqueiros");

        grupo_questao_4.add(rbQ4Nao);
        rbQ4Nao.setText("Não");

        ckbQ4PorSobreposicaoDeRedeEEspinhel.setText("Por sobreposição de rede e espinhel");

        ckbQ4PorSobreposicaodeRedes.setText("Por sobreposição de redes");

        grupo_questao_5.add(rbQ5Sim);
        rbQ5Sim.setText("Sim");

        grupo_questao_5.add(rbQ5Nao);
        rbQ5Nao.setText("Não. Por que?");

        jLabel29.setText("5 - Pretende continuar na atividade?");

        jLabel30.setText("6 - Existem conflitos com instituições (IBAMA, MPA, SEPAQ)? Quais instituições e descrever conflitos.");

        taQuestao6.setColumns(20);
        taQuestao6.setRows(5);
        jScrollPane6.setViewportView(taQuestao6);

        jLabel31.setText("7 - O que mudeou na pescaria nos últimos 10 anos? Como era a 10 anos atrás?");

        taQuestao7.setColumns(20);
        taQuestao7.setRows(5);
        jScrollPane7.setViewportView(taQuestao7);

        jLabel32.setText("8 - O que está acontecendo com o tamanho e a quantidade de pescado?");

        taQuestao8.setColumns(20);
        taQuestao8.setRows(5);
        jScrollPane8.setViewportView(taQuestao8);

        jLabel33.setText("9 - Qual o motivo dessas mudanças?");

        taQuestao9.setColumns(20);
        taQuestao9.setRows(5);
        jScrollPane9.setViewportView(taQuestao9);

        jLabel34.setText("10 - O que acha que deveria ser feito pra solucionar?");

        taQuestao10.setColumns(20);
        taQuestao10.setRows(5);
        jScrollPane10.setViewportView(taQuestao10);

        jLabel35.setText("11 - Que perspectivas você tem vê para os próximos anos?");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        g11.add(ckbQuestao11DeCrescimento);
        ckbQuestao11DeCrescimento.setText("De crescimento");

        g11.add(ckbQuestao11Estabilizacao);
        ckbQuestao11Estabilizacao.setText("De Estabilização");

        g11.add(ckbQuestao11DeDiminuicao);
        ckbQuestao11DeDiminuicao.setText("De Diminuição");

        grupo_questao_1.add(rbq1ns);
        rbq1ns.setText("n/s");

        grupo_questao_2.add(rbq2ns);
        rbq2ns.setText("n/s");

        g11.add(rbQ11ns);
        rbQ11ns.setText("n/s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPescador, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckbQ3TrocadeOleo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbQ3TrocadePescado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbQ3TrocadeAlimentos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbQ3Rebocar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbQ3Outros))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbQ3Sim)
                                        .addGap(56, 56, 56)
                                        .addComponent(rbQ3Nao))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(rbQ2Aumentando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbQ2Diminuindo)
                        .addGap(18, 18, 18)
                        .addComponent(rbq2ns))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(rbQ1sim)
                        .addGap(52, 52, 52)
                        .addComponent(rbQ1nao)
                        .addGap(44, 44, 44)
                        .addComponent(rbq1ns))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckbQ4PorSobreposicaoDeRedeEEspinhel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ckbQ4PorRoubodeRede)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ckbQ4Outros))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckbQ4PorPesqueiros)
                                            .addComponent(rbQ4Sim))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbQ4Nao)
                                            .addComponent(ckbQ4PorSobreposicaodeRedes)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ5Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbQ5Nao))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel31)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel32)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel33)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckbQuestao11DeCrescimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckbQuestao11Estabilizacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckbQuestao11DeDiminuicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbQ11ns))
                            .addComponent(jLabel35)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPescador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbQ1sim)
                    .addComponent(rbQ1nao)
                    .addComponent(rbq1ns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbQ2Aumentando)
                    .addComponent(rbQ2Diminuindo)
                    .addComponent(rbq2ns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbQ3Sim)
                    .addComponent(rbQ3Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ3TrocadeOleo)
                    .addComponent(ckbQ3TrocadePescado)
                    .addComponent(ckbQ3TrocadeAlimentos)
                    .addComponent(ckbQ3Rebocar)
                    .addComponent(ckbQ3Outros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbQ4Sim)
                    .addComponent(rbQ4Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ4PorPesqueiros)
                    .addComponent(ckbQ4PorSobreposicaodeRedes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQ4PorSobreposicaoDeRedeEEspinhel)
                    .addComponent(ckbQ4PorRoubodeRede)
                    .addComponent(ckbQ4Outros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(rbQ5Sim)
                    .addComponent(rbQ5Nao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbQuestao11DeCrescimento)
                    .addComponent(ckbQuestao11Estabilizacao)
                    .addComponent(ckbQuestao11DeDiminuicao)
                    .addComponent(rbQ11ns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btAtualizar))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-779)/2, (screenSize.height-516)/2, 779, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar_janela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar_janela
        conexao.desconecta();
    }//GEN-LAST:event_fechar_janela

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        salvar_dados();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizar_dados();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void cbPescadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPescadorItemStateChanged
        
    }//GEN-LAST:event_cbPescadorItemStateChanged

    private void cbPescadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPescadorActionPerformed
        if (inicia_combo == 1){
            mostra_dados();
        }
        inicia_combo = 1;
    }//GEN-LAST:event_cbPescadorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pescador3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbPescador;
    private javax.swing.JCheckBox ckbQ3Outros;
    private javax.swing.JCheckBox ckbQ3Rebocar;
    private javax.swing.JCheckBox ckbQ3TrocadeAlimentos;
    private javax.swing.JCheckBox ckbQ3TrocadeOleo;
    private javax.swing.JCheckBox ckbQ3TrocadePescado;
    private javax.swing.JCheckBox ckbQ4Outros;
    private javax.swing.JCheckBox ckbQ4PorPesqueiros;
    private javax.swing.JCheckBox ckbQ4PorRoubodeRede;
    private javax.swing.JCheckBox ckbQ4PorSobreposicaoDeRedeEEspinhel;
    private javax.swing.JCheckBox ckbQ4PorSobreposicaodeRedes;
    private javax.swing.JRadioButton ckbQuestao11DeCrescimento;
    private javax.swing.JRadioButton ckbQuestao11DeDiminuicao;
    private javax.swing.JRadioButton ckbQuestao11Estabilizacao;
    private javax.swing.ButtonGroup g11;
    private javax.swing.ButtonGroup grupo_questao_1;
    private javax.swing.ButtonGroup grupo_questao_2;
    private javax.swing.ButtonGroup grupo_questao_3;
    private javax.swing.ButtonGroup grupo_questao_4;
    private javax.swing.ButtonGroup grupo_questao_5;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbQ11ns;
    private javax.swing.JRadioButton rbQ1nao;
    private javax.swing.JRadioButton rbQ1sim;
    private javax.swing.JRadioButton rbQ2Aumentando;
    private javax.swing.JRadioButton rbQ2Diminuindo;
    private javax.swing.JRadioButton rbQ3Nao;
    private javax.swing.JRadioButton rbQ3Sim;
    private javax.swing.JRadioButton rbQ4Nao;
    private javax.swing.JRadioButton rbQ4Sim;
    private javax.swing.JRadioButton rbQ5Nao;
    private javax.swing.JRadioButton rbQ5Sim;
    private javax.swing.JRadioButton rbq1ns;
    private javax.swing.JRadioButton rbq2ns;
    private javax.swing.JTextArea taQuestao10;
    private javax.swing.JTextArea taQuestao5;
    private javax.swing.JTextArea taQuestao6;
    private javax.swing.JTextArea taQuestao7;
    private javax.swing.JTextArea taQuestao8;
    private javax.swing.JTextArea taQuestao9;
    // End of variables declaration//GEN-END:variables


    private void mostra_dados(){
        limpar_dados();
        String codigo = util.separa(1,cbPescador.getSelectedItem().toString());
        System.out.println(codigo);
        try {
            //Pescador Moradia
            conexao.execute("SELECT * FROM pescador_perspectiva WHERE cod_pescador = "+codigo);
            conexao.resultSet.first();

            //Selecionar os check boxes conforme o BD
            String testador = new String();

            testador = conexao.resultSet.getString("questao1");
            if (testador.equals("sim"))
                   rbQ1sim.setSelected(true);
            else
                   rbQ1sim.setSelected(false);

            if (testador.equals("não"))
                   rbQ1nao.setSelected(true);
            else
                   rbQ1nao.setSelected(false);

            if (testador.equals("n/s"))
                   rbq1ns.setSelected(true);
            else
                   rbq1ns.setSelected(false);

            testador = conexao.resultSet.getString("questao2");
            if (testador.equals("aumentando"))
                   rbQ2Aumentando.setSelected(true);
            else
                   rbQ2Aumentando.setSelected(false);

            if (testador.equals("diminuindo"))
                   rbQ2Diminuindo.setSelected(true);
            else
                   rbQ2Diminuindo.setSelected(false);

            if (testador.equals("n/s"))
                   rbq2ns.setSelected(true);
            else
                   rbq2ns.setSelected(false);

            testador = conexao.resultSet.getString("questao3");
            if (!testador.equals(""))
                   rbQ3Sim.setSelected(true);
            else
                   rbQ3Sim.setSelected(false);

            if (testador.equals(""))
                   rbQ3Nao.setSelected(true);
            else
                   rbQ3Nao.setSelected(false);

            if (testador.equals("Troca de óleo"))
                   ckbQ3TrocadeOleo.setSelected(true);
            else
                   ckbQ3TrocadeOleo.setSelected(false);

            if (testador.equals("Troca de pescado ou grude"))
                   ckbQ3TrocadePescado.setSelected(true);
            else
                   ckbQ3TrocadePescado.setSelected(false);

            if (testador.equals("Troca de alimentos"))
                   ckbQ3TrocadeAlimentos.setSelected(true);
            else
                   ckbQ3TrocadeAlimentos.setSelected(false);

            if (testador.equals("Rebocar"))
                   ckbQ3Rebocar.setSelected(true);
            else
                   ckbQ3Rebocar.setSelected(false);

            if (testador.equals("Outros"))
                   ckbQ3Outros.setSelected(true);
            else
                   ckbQ3Outros.setSelected(false);
            
            testador = conexao.resultSet.getString("questao4");
            if (!testador.equals(""))
                   rbQ4Sim.setSelected(true);
            else
                   rbQ4Sim.setSelected(false);

            if (testador.equals(""))
                   rbQ4Nao.setSelected(true);
            else
                   rbQ4Nao.setSelected(false);

            if (testador.equals("Por pesqueiros"))
                   ckbQ4PorPesqueiros.setSelected(true);
            else
                   ckbQ4PorPesqueiros.setSelected(false);

            if (testador.equals("Por sobreposição de redes"))
                   ckbQ4PorSobreposicaodeRedes.setSelected(true);
            else
                   ckbQ4PorSobreposicaodeRedes.setSelected(false);

            if (testador.equals("Por sobreposição de rede e espinhel"))
                   ckbQ4PorSobreposicaoDeRedeEEspinhel.setSelected(true);
            else
                   ckbQ4PorSobreposicaoDeRedeEEspinhel.setSelected(false);

            if (testador.equals("Por roubo de rede"))
                   ckbQ4PorRoubodeRede.setSelected(true);
            else
                   ckbQ4PorRoubodeRede.setSelected(false);

            if (testador.equals("Outros"))
                   ckbQ4Outros.setSelected(true);
            else
                   ckbQ4Outros.setSelected(false);

            testador = conexao.resultSet.getString("questao5");
            if (!testador.equals(""))
                   rbQ5Sim.setSelected(true);
            else
                   rbQ5Sim.setSelected(false);

            if (testador.equals(""))
                   rbQ5Nao.setSelected(true);
            else
                   rbQ5Nao.setSelected(false);

            taQuestao5.setText(testador);

            taQuestao6.setText(conexao.resultSet.getString("questao6"));

            taQuestao7.setText(conexao.resultSet.getString("questao7"));

            taQuestao8.setText(conexao.resultSet.getString("questao8"));

            taQuestao9.setText(conexao.resultSet.getString("questao9"));

            taQuestao10.setText(conexao.resultSet.getString("questao10"));

            testador = conexao.resultSet.getString("questao11");
            if (testador.equals("De crescimento"))
                   ckbQuestao11DeCrescimento.setSelected(true);
            else
                   ckbQuestao11DeCrescimento.setSelected(false);

            if (testador.equals("Estabilização"))
                   ckbQuestao11Estabilizacao.setSelected(true);
            else
                   ckbQuestao11Estabilizacao.setSelected(false);

            if (testador.equals("De diminuição"))
                   ckbQuestao11DeDiminuicao.setSelected(true);
            else
                   ckbQuestao11DeDiminuicao.setSelected(false);

            if (testador.equals("n/s"))
                   rbQ11ns.setSelected(true);
            else
                   rbQ11ns.setSelected(false);

        }catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null,"Nenhum registro encontrado "+ ex );
                System.out.println("Erro no mostrar dados");               
        }

    }

    private void attCbPescador() {
        try {
            cbPescador.removeAllItems();
            conexao.execute("select * from pescador");

            while (conexao.resultSet.next()){
                cbPescador.addItem(conexao.resultSet.getString("cod_pescador")+
                            " # "+ conexao.resultSet.getString("nome"));
            }

        }catch (SQLException ex) {
            System.out.println("Erro no cbPescador "+ex);
        }
    }

    private void limpar_dados() {
        
        rbQ1sim.setSelected(false);
        rbQ1nao.setSelected(false);
        rbq1ns.setSelected(false);
        rbQ2Aumentando.setSelected(false);
        rbQ2Diminuindo.setSelected(false);
        rbq2ns.setSelected(false);
        rbQ3Sim.setSelected(false);
        rbQ3Nao.setSelected(false);
        ckbQ3TrocadeOleo.setSelected(false);
        ckbQ3TrocadePescado.setSelected(false);
        ckbQ3TrocadeAlimentos.setSelected(false);
        ckbQ3Rebocar.setSelected(false);
        ckbQ3Outros.setSelected(false);
        rbQ4Sim.setSelected(false);
        rbQ4Nao.setSelected(false);
        ckbQ4PorPesqueiros.setSelected(false);
        ckbQ4PorSobreposicaodeRedes.setSelected(false);
        ckbQ4PorSobreposicaoDeRedeEEspinhel.setSelected(false);
        ckbQ4PorRoubodeRede.setSelected(false);
        ckbQ4Outros.setSelected(false);
        rbQ4Sim.setSelected(false);
        rbQ4Nao.setSelected(false);
        taQuestao5.setText("");
        taQuestao6.setText("");
        taQuestao7.setText("");
        taQuestao8.setText("");
        taQuestao9.setText("");
        taQuestao10.setText("");
        ckbQuestao11DeCrescimento.setSelected(false);
        ckbQuestao11Estabilizacao.setSelected(false);
        ckbQuestao11DeDiminuicao.setSelected(false);
        rbQ11ns.setSelected(false);

    }

    private void salvar_dados() {
    String codigo = util.separa(1,cbPescador.getSelectedItem().toString());
    System.out.println(codigo);

          //Tabela Locais da composição pescaria
          //Pegando ites do CB

            String q1 = new String();
            if (rbQ1sim.isSelected())
                   q1 = "sim";
            else if (rbQ1nao.isSelected())
                   q1 = "não";
            else if (rbq1ns.isSelected())
                   q1 = "n/s";


            String q2 = new String();
            if (rbQ2Aumentando.isSelected())
                   q2 = "aumentando";
            else if (rbQ2Diminuindo.isSelected())
                   q2 = "diminuindo";
            else if (rbq2ns.isSelected())
                   q2 = "n/s";

            String q3 = new String();
            if (ckbQ3TrocadeOleo.isSelected())
                   q3 = "Troca de óleo";
            else if (ckbQ3TrocadePescado.isSelected())
                   q3 = "Troca de pescado ou grude";
            else if (ckbQ3TrocadeAlimentos.isSelected())
                   q3 = "Troca de alimentos";
            else if (ckbQ3Rebocar.isSelected())
                   q3 = "Rebocar";
            else if (ckbQ3Outros.isSelected())
                   q3 = "Outros";

            String q4 = new String();
            if (ckbQ4PorPesqueiros.isSelected())
                   q4 = "Por pesqueiros";
            else if (ckbQ4PorSobreposicaodeRedes.isSelected())
                   q4 = "Por sobreposição de redes";
            else if (ckbQ4PorSobreposicaoDeRedeEEspinhel.isSelected())
                   q4 = "Por sobreposição de rede e espinhel";
            else if (ckbQ4PorRoubodeRede.isSelected())
                   q4 = "Por roubo de rede";
            else if (ckbQ4Outros.isSelected())
                   q4 = "Outros";

            String q11 = new String();
            if (ckbQ4PorPesqueiros.isSelected())
                   q11 = "De crescimento";
            else if (ckbQ4PorSobreposicaodeRedes.isSelected())
                   q11 = "Estabilização";
            else if (ckbQ4PorSobreposicaoDeRedeEEspinhel.isSelected())
                   q11 = "De diminuição";
            else if (rbQ11ns.isSelected())
                   q11 = "n/s";
         
            String sqlinsert = "insert into pescador_perspectiva "
                    + "(cod_pescador,questao1,questao2,questao3,"
                    + "questao4,questao5,questao6,questao7,"
                    + "questao8,questao9,questao10,questao11"
                    +  ") values ("+
                    codigo+",'"+
                    q1+"','"+
                    q2+"','"+
                    q3+"','"+
                    q4+"','"+
                    taQuestao5.getText()+"','"+
                    taQuestao6.getText()+"','"+
                    taQuestao7.getText()+"','"+
                    taQuestao8.getText()+"','"+
                    taQuestao9.getText()+"','"+
                    taQuestao10.getText()+"','"+
                    q11+"')";

            //System.out.println(sqlinsert);
            if (conexao.salvar(sqlinsert)) {
                JOptionPane.showMessageDialog(null,"Salvo com sucesso");
                System.out.println("Pescador Perspectiva - Cadastrado com sucesso");
                mostra_dados();
            }


    }

    private void atualizar_dados() {
    String codigo = util.separa(1,cbPescador.getSelectedItem().toString());
    System.out.println(codigo);

          //Tabela Locais da composição pescaria
          //Pegando ites do CB

            String q1 = new String();
            if (rbQ1sim.isSelected())
                   q1 = "sim";
            else if (rbQ1nao.isSelected())
                   q1 = "não";
            else if (rbq1ns.isSelected())
                   q1 = "n/s";

            String q2 = new String();
            if (rbQ2Aumentando.isSelected())
                   q2 = "aumentando";
            else if (rbQ2Diminuindo.isSelected())
                   q2 = "diminuindo";
            else if (rbq2ns.isSelected())
                   q2 = "n/s";

            String q3 = new String();
            if (ckbQ3TrocadeOleo.isSelected())
                   q3 = "Troca de óleo";
            else if (ckbQ3TrocadePescado.isSelected())
                   q3 = "Troca de pescado ou grude";
            else if (ckbQ3TrocadeAlimentos.isSelected())
                   q3 = "Troca de alimentos";
            else if (ckbQ3Rebocar.isSelected())
                   q3 = "Rebocar";
            else if (ckbQ3Outros.isSelected())
                   q3 = "Outros";

            String q4 = new String();
            if (ckbQ4PorPesqueiros.isSelected())
                   q4 = "Por pesqueiros";
            else if (ckbQ4PorSobreposicaodeRedes.isSelected())
                   q4 = "Por sobreposição de redes";
            else if (ckbQ4PorSobreposicaoDeRedeEEspinhel.isSelected())
                   q4 = "Por sobreposição de rede e espinhel";
            else if (ckbQ4PorRoubodeRede.isSelected())
                   q4 = "Por roubo de rede";
            else if (ckbQ4Outros.isSelected())
                   q4 = "Outros";

            String q11 = new String();
            if (ckbQuestao11DeCrescimento.isSelected())
                   q11 = "De crescimento";
            else if (ckbQuestao11Estabilizacao.isSelected())
                   q11 = "Estabilização";
            else if (ckbQuestao11DeDiminuicao.isSelected())
                   q11 = "De diminuição";
            else if (rbQ11ns.isSelected())
                   q11 = "n/s";

        String sqlupdate ="UPDATE pescador_perspectiva SET "
                    +"questao1 = '"+q1+"',"
                    +"questao2 = '"+q2+"',"
                    +"questao3 = '"+q3+"',"
                    +"questao4 = '"+q4+"',"
                    +"questao5 = '"+taQuestao5.getText()+"',"
                    +"questao6 = '"+taQuestao6.getText()+"',"
                    +"questao7 = '"+taQuestao7.getText()+"',"
                    +"questao8 = '"+taQuestao8.getText()+"',"
                    +"questao9 = '"+taQuestao9.getText()+"',"
                    +"questao10 = '"+taQuestao10.getText()+"',"
                    +"questao11 = '"+q11+"' "+

                    "where cod_pescador = "+codigo;

            //System.out.println(sqlupdate);
            if (conexao.update(sqlupdate)){
                JOptionPane.showMessageDialog(null,"Alterado com sucesso");
                System.out.println("Atualizado com sucesso");
                mostra_dados();
            }
    }

}
